spring.application.name=lms-portal
#debug=true

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lms-portal-db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true